Hue_low : 0 
Hue_high : 179 
Saturation_low : 68 
Saturation_high : 255 
Value_low : 138 
Value_high : 255 
gray_thresh : 0 
number_of_lines : 37 
error_threshold : 0.32 
Width_min : 10 
Width_max : 500 
inverted_filter : 0 
camera_start_height : 300 
camera_bottom_height : 600 
camera_left_width : 0 
camera_right_width : 800 
steering_sensitivity : 0.53 
zero_throttle : 0.07000000000000006 
no_error_throttle : 0.17599999999999993 
error_throttle : 0.16700000000000004 
